services:
  consul-agent:
    container_name: consul
    image: hashicorp/consul:latest
    ports:
      - 8500:8500
      - 8600:8600/udp
    command: agent -server -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0

  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    container_name: kafka
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_CREATE_TOPICS: "ratings:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  metadata-db:
    container_name: metadata-db
    image: postgres:16.3-alpine
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=metadata_db
    volumes:
      - ./data/metadata/:/var/lib/postgresql/data
      - ./dbscripts/metadata_public_schema.sql:/docker-entrypoint-initdb.d/public_schema.sql

  ratings-db:
    container_name: ratings-db
    image: postgres:16.3-alpine
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=ratings_db
    volumes:
      - ./data/ratings/:/var/lib/postgresql/data
      - ./dbscripts/ratings_public_schema.sql:/docker-entrypoint-initdb.d/public_schema.sql